repl: write to stderr on error

diff --git a/bin/repl b/bin/repl
--- a/bin/repl
+++ b/bin/repl
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 if [ ! "$(command -v "$1")" ] ; then
-  echo "$1 not found" && exit 1
+  echo "$1 not found" 1>&2 && exit 1
 fi
 
 while true ; do
